"""
Position Domain Model and Accounting
"""
from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional
from modules.execution.fills import Fill
from modules.execution.order import OrderSide


@dataclass
class Position:
    symbol: str
    quantity: int = 0
    avg_price: float = 0.0
    cost_basis: float = 0.0
    realized_pnl: float = 0.0
    total_commission: float = 0.0
    total_tax: float = 0.0
    last_price: float = 0.0
    updated_at: datetime = field(default_factory=datetime.now)

    def apply_fill(self, fill: Fill) -> float:
        """
        Applies a Fill event to the position.
        Returns the realized PnL generated by this fill (if any).
        """
        if fill.symbol != self.symbol:
            raise ValueError(f"Symbol mismatch: position is for {self.symbol}, fill is for {fill.symbol}")

        fill_realized_pnl = 0.0

        if fill.side == OrderSide.BUY:
            new_quantity = self.quantity + fill.quantity
            new_cost = self.cost_basis + fill.gross_value
            self.quantity = new_quantity
            self.cost_basis = new_cost
            self.avg_price = new_cost / new_quantity if new_quantity > 0 else 0.0
            self.total_commission += fill.commission
            self.total_tax += fill.tax

        elif fill.side == OrderSide.SELL:
            if fill.quantity > self.quantity:
                raise ValueError(
                    f"Overselling position {self.symbol}: holding {self.quantity}, selling {fill.quantity}"
                )

            # Realized PnL = (sell price - avg buy price) * shares - costs
            trade_pnl = (fill.price - self.avg_price) * fill.quantity
            net_trade_pnl = trade_pnl - fill.commission - fill.tax
            fill_realized_pnl = net_trade_pnl

            self.realized_pnl += net_trade_pnl
            self.quantity -= fill.quantity
            if self.quantity == 0:
                self.cost_basis = 0.0
                self.avg_price = 0.0
            else:
                self.cost_basis = self.avg_price * self.quantity

            self.total_commission += fill.commission
            self.total_tax += fill.tax

        self.last_price = fill.price
        self.updated_at = datetime.now()
        return fill_realized_pnl

    def market_value(self, current_price: Optional[float] = None) -> float:
        price = current_price if current_price is not None else self.last_price
        return self.quantity * price

    def unrealized_pnl(self, current_price: Optional[float] = None) -> float:
        if self.quantity == 0:
            return 0.0
        price = current_price if current_price is not None else self.last_price
        return (price - self.avg_price) * self.quantity
